name: control
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  cupertino_icons: ^1.0.8
  dio: ^5.9.0
  freezed: ^3.2.3
  flutter_secure_storage: ^9.2.4
  camera: ^0.11.2
  provider: ^6.1.5+1
  go_router: ^16.2.4
  freezed_annotation: ^3.1.0
  hooks_riverpod: ^3.0.0
  riverpod_annotation: ^3.0.0
  flutter_hooks:
  uuid: ^4.5.1
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.7.1
  json_serializable: ^6.11.1
  riverpod_generator: ^3.0.0
  go_router_builder: ^4.1.0
  build_verify: any

flutter:
  uses-material-design: true
